state_choices = {
    'AL': 'Alabama',
    'AK': 'Alask',
    'AZ': 'Arizo',
    'AR': 'Arkan',
    'CA': 'Calif',
    'CO': 'Color',
    'CT': 'Conne',
    'DE': 'Delaw',
    'DC': 'Distr',
    'FL': 'Flori',
    'GA': 'Georg',
    'HI': 'Hawai',
    'ID': 'Idaho',
    'IL': 'Illin',
    'IN': 'India',
    'IA': 'Iowa',
    'KS': 'Kansa',
    'KY': 'Kentu',
    'LA': 'Louis',
    'ME': 'Maine',
    'MD': 'Maryl',
    'MA': 'Massa',
    'MI': 'Michi',
    'MN': 'Minne',
    'MS': 'Missi',
    'MO': 'Misso',
    'MT': 'Monta',
    'NE': 'Nebra',
    'NV': 'Nevad',
    'NH': 'New H',
    'NJ': 'New J',
    'NM': 'New M',
    'NY': 'New Y',
    'NC': 'North',
    'ND': 'North',
    'OH': 'Ohio',
    'OK': 'Oklah',
    'OR': 'Orego',
    'PA': 'Penns',
    'RI': 'Rhode',
    'SC': 'South',
    'SD': 'South',
    'TN': 'Tenne',
    'TX': 'Texas',
    'UT': 'Utah<',
    'VT': 'Vermo',
    'VA': 'Virgi',
    'WA': 'Washi',
    'WV': 'West ',
    'WI': 'Wisco',
    'WY': 'Wyom'
}

bedrooms_choices = {
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10'
}

price_choices = {
    '100000': '$100,000',
    '200000': '$200,000',
    '300000': '$300,000',
    '400000': '$400,000',
    '500000': '$500,000',
    '600000': '$600,000',
    '700000': '$700,000',
    '800000': '$800,000',
    '900000': '$900,000',
    '1000000': '$1M+'
}
